FASTBOOT_ERROR_HINTS = [
    ("waiting for device", "等待设备连接，未检测到处于 fastboot 模式的设备。"),
    ("no devices found", "未发现设备，连接失败或设备未进入 fastboot 模式。"),
    ("FAILED (status read failed (No such device))", "设备连接中断，可能是 USB 线松动或设备退出模式。"),
    ("error: device not found", "未找到设备，驱动或连接存在问题。"),
    ("No link", "设备与电脑数据链路未建立，连接不稳定或模式异常。"),
    ("remote: oem unlock is not allowed", "未开启“允许 OEM 解锁”，需在开发者选项中开启。"),
    ("command not allowed", "命令不被允许，通常因未解锁 Bootloader 或权限不足。"),
    ("remote: unlock is not allowed", "不允许解锁，可能设备限制或未满足解锁条件。"),
    ("permission denied", "权限不足，电脑端需用管理员权限运行命令。"),
    ("remote: insufficient permissions", "权限不足，操作被系统拒绝。"),
    ("remote: device is locked. Cannot flash images", "设备未解锁，无法刷写镜像。"),
    ("invalid sparse file format at header magic", "镜像文件格式错误，可能损坏或非稀疏文件。"),
    ("cannot load", "无法加载指定镜像，文件不存在、路径错误或损坏。"),
    ("invalid argument", "命令参数错误，输入的命令格式或参数不符合要求。"),
    ("unknown command", "命令不存在，输入的指令拼写错误或不被支持。"),
    ("FAILED (data transfer failure (Unknown error))", "数据传输失败，可能因文件损坏或连接中断。"),
    ("remote: image is not a sparse file", "镜像非稀疏文件，设备仅支持稀疏格式镜像。"),
    ("Too many links", "多出现于大文件传输分片时，可能因传输链路问题导致分片处理异常。"),
    ("remote: partition table doesn't exist", "分区表不存在，可能分区表损坏。"),
    ("failed to erase partition", "擦除分区失败，分区损坏或硬件问题。"),
    ("remote: flash write failure", "写入失败，可能存储芯片故障或镜像不兼容。"),
    ("remote: partition not found", "指定分区不存在，命令中的分区名错误。"),
    ("remote: size mismatch", "镜像大小与分区不匹配，镜像不适配设备。"),
    ("remote: invalid partition name", "分区名无效，输入的分区名称错误。"),
    ("FAILED (erase failed)", "擦除操作失败，分区无法被正常擦除。"),
    ("remote: failed to write to partition", "写入分区失败，分区损坏或权限问题。"),
    ("remote: security version mismatch", "安全版本不匹配，镜像与设备安全版本冲突。"),
    ("remote: downgrade is not allowed", "不允许降级，镜像版本低于设备当前版本且受限制。"),
    ("FAILED (unknown status code)", "未知状态码，错误原因不明确，需排查连接和命令。"),
    ("remote: signature verification failed", "签名验证失败，镜像未通过官方签名校验。"),
    ("remote: security downgrade is not allowed", "不允许安全降级，镜像安全级别低于设备要求。")
] 